### ISSUE TITLE
hr_uids are incorrect in BC and now inconsistent with CovidTimelineCanada

### ISSUE THREAD

**Issue by apiology** [andrewthong/covid19tracker-api#118]
Hi!

This is an issue to track the problem discovered by [jeanpaulrsoucy](https://github.com/jeanpaulrsoucy) in https://github.com/ccodwg/CovidTimelineCanada/issues/23#issuecomment-1140359374

Per his note:

> The health region IDs for BC used by covid19tracker.ca are wrong: https://api.covid19tracker.ca/province/BC/regions
> ...but this traces back to the health region IDs for BC used by us in Covid19Canada being wrong: https://github.com/ccodwg/Covid19Canada/blob/master/other/hr_map.csv
> ...but this traces back to the health region IDs for BC used by ESRI (for their map file) being wrong: https://resources-covid19canada.hub.arcgis.com/datasets/covid19canada::health-region-summaries

> However, [CovidTimelineCanada's] current HRUIDs for BC are now correct, according to both [StatCan](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710013401) and [BC itself](https://catalogue.data.gov.bc.ca/dataset/health-authority-boundaries).

He notes that he has reached out to @noahlittle on this.  This issue is currently blocking microCOVID.org from being able to report at the health-region level: https://github.com/microCOVID/microCOVID/pull/1452

**Comment by noahlittle** [comment]
This issue should be resolved now! We revised the incorrect HRUIDs over the weekend and they should be reflected in our API now.
