### ISSUE TITLE
Quebec Data - Total tests are actually number of people tested

### ISSUE THREAD

**Issue by jell-byte** [andrewthong/covid19tracker-api#34]
Hello folks,

First of all, thanks a lot for publicly providing that API. It's very well documented and great to work with. :)

I was having a look at the API and went over the data in [Quebec](https://api.covid19tracker.ca/reports/province/QC) to look how it compares to the reported numbers. In that regard, I noticed that the change_tests and total_tests do not expose the values that I would expect.
I think the reason is that they do not refer to the number of tests, but rather the number of people tested (which can be quite different as someone might be tested multiple times).
This can be seen quite well on https://www.inspq.qc.ca/covid-19/donnees where the number your API provides correspond to the 4.1 section which describes the number of people tested positive and negative. However, the plot at 4.2, which shows the number of tests, is quite different from the API values.
This can also be seen at https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/#c51841 where the total number of tests stated on the website for August 10 is 1,394,431 (see below). This is much more than the number exposed by the API (926,538 for August 12).
![image](https://user-images.githubusercontent.com/69625164/90116053-389d1a00-dd55-11ea-8a43-414efc5a3f36.png)

Would it be possible to integrate the total number of tests instead or in addition to the number of people tested? I think this number is very valuable as it describes the current capabilities of laboratories much better.

Best,
Georg

**Comment by noahlittle** [comment]
Hi Georg,

I'm happy to hear that you're using the API and that it's meeting your needs.

Whenever possible, we try to report the number of people tested to allow for calculations as a proportion of population. However you bring up a great point regarding laboratory capacity. As such, we'll begin tracking the number of tests done separately, though historical data may be unavailable. This will be added as a part of the existing endpoint soon.

Thank you for your suggestion!

Noah

**Comment by jell-byte** [comment]
Hey Noah,

Thanks a lot for your response and consideration. That's great to hear!

Best,
Georg

**Comment by noahlittle** [comment]
Testing data for Quebec has now been replaced to reflect the total number of tests.
