### ISSUE TITLE
No stats by city

### ISSUE THREAD

**Issue by HCLarsen** [andrewthong/covid19tracker-api#37]
I see that there's city info in the individual cases, but I don't see any endpoints to get totals by city. If this isn't added yet, it may prove useful.

**Comment by andrewthong** [comment]
There is a recent addition to support health regions in the data. Not exactly cities, but would provide more granularity beyond the province. The data should be available soon.

**Comment by HCLarsen** [comment]
Yes, regions would helpful, thank you.

**Comment by andrewthong** [comment]
Health region support has been rolled out.
https://api.covid19tracker.ca/docs/1.0/regions
