### ISSUE TITLE
Unfamiliar with retrieving a specific province's report

### ISSUE THREAD

**Issue by koreankim** [andrewthong/covid19tracker-api#38]
Hello,

In your API docs, it shows that when getting `https://api.covid19tracker.ca/reports?fill_dates&stat=&date&after&before`, it returns data from ALL provinces. Is there a way to specify a province? 

Cheers,

**Comment by noahlittle** [comment]
Hi there,

The report for a specific province can be called using the following format:

`https://api.covid19tracker.ca/reports/province/sk`

Note that 'sk' can be replaced with any province code to return the data for that specific province. 

All the best!
