### ISSUE TITLE
All endpoints to return "last_updated"

### ISSUE THREAD

**Issue by geoffreyjball** [andrewthong/covid19tracker-api#42]
The `/summary` endpoint returns a "last_updated" value. It would be great if others (especially `/reports`) returned that value, as well. Specifically, I'm pulling Alberta data and looking for null values or zero length arrays to judge if the content is added for the current day (and popping the array if it isn't). It would be helpful to have that field instead.

**Comment by andrewthong** [comment]
I am considering a rework to last_updated to cover the data at least at province/health region level. Right now that timestamp is sitewide and based on when the report processing utility was last run.
