### ISSUE TITLE
API for vaccine data

### ISSUE THREAD

**Issue by jeromegv** [andrewthong/covid19tracker-api#45]
Hello

Is your vaccination tracker available through an API?

Thank you

**Comment by noahlittle** [comment]
Yes - all of the vaccination tracker data is available via our API as a part of standard endpoints for `reports` and includes cumulative and change in vaccinations nationally, for each province and for some health regions as reported.

Documentation that may assist you: https://api.covid19tracker.ca/docs/1.0/reports
