### ISSUE TITLE
Any data to differentiate first and second dose?

### ISSUE THREAD

**Issue by fbeaulieuusi** [andrewthong/covid19tracker-api#65]
Hi
I would need the number of people "fully" vaccinated with two doses.
I haven't found the definition for change_vaccinations and change_vaccines_distributed, maybe the answer is there but i'm not sure.
Thank you for your good work

**Comment by andrewthong** [comment]
We recently added a `vaccinated` stat. I still haven't go around to updating the documentation. But essentially,

- vaccinations: people administered at least one dose
- vaccinated: people given the second dose (though if there are single-dose vaccines this will include that number)
- vaccines_distributed: count of vaccines distributed in the given region

**Comment by fbeaulieuusi** [comment]
Thanks Andrew!
