### ISSUE TITLE
health region data should include population and other demographic data

### ISSUE THREAD

**Issue by colinbendell** [andrewthong/covid19tracker-api#68]
health region data from stats canada should be included in the /hr results. This data can be picked up from:
`https://www12.statcan.gc.ca/rest/census-recensement/CR2016Geo.json?geos=HR` . Each Health Region ID can be used to call `https://www12.statcan.gc.ca/rest/census-recensement/CPR2016.json?dguid=${hr[0]}&topic=13` to collect the last census population values.

**Comment by andrewthong** [comment]
If demographic data is needed, I would advise to source it from statscan for up to date info.

**Comment by colinbendell** [comment]
I'm pointing out that your data model doesn't match stats can, and since you've included non health region zones (namely saskatchewan), your data model should accommodate this representation to match the /provinces end point schema. Also, stats canada data is based on 2016 census
