### ISSUE TITLE
health regions don't match current health region definitions

### ISSUE THREAD

**Issue by colinbendell** [andrewthong/covid19tracker-api#69]
It appears that the health region data uses a hybrid of 2016 census health region/unit definition and current configurations. For example, Saskatchewan used to have 13 health regions, but currently has only one health unit. Yet, the health region data breaks it down by 6 sub divisions. the hr_uid for these itemsdoesn't appear to match the official hr_uid.

**Comment by noahlittle** [comment]
HR UIDs are based solely upon the availability of data and COVID-19 reporting standards for each province. It is only possible to provide data for regions where data is available, and only to the granularity with which this data is released.

The current breakdown is the most granular possible with full, historical data throughout the pandemic for each health region.

**Comment by colinbendell** [comment]
HR UIDs are based on stats canada's unique identifcation and breakdown. After further review, it looks like SK's break down is not actually health regions, but health zones populated just for covid reporting. This came into effect in August of 2020 and was subsequently updated with further zone breakdowns. I think it would be good to declare which data items are real health regions vs. temporary health zones. Particularly when aligning this data with census or population data.

**Comment by noahlittle** [comment]
The HR UIDs are used for convenience, but as-is standard with regional COVID reporting in Canada, everything is based upon the regions that each province reports COVID-19 data for. There is no other data or breakdown possible besides what is reported by the provinces. The full name of the region, as used in provincial COVID-19 reporting, is returned with the /regions endpoint. HR UIDs are provided for convenience.

SK, like some other provinces, operates under a single health authority, and has modified the zones it reports for multiple times - even prior to August 2020. For consistency and availability of historical data, we use the original 6 zones reported - there is no historical data available for the expanded zones prior to August 2020.
