### ISSUE TITLE
Data issue (Ottawa May 28)

### ISSUE THREAD

**Issue by Drewnonymous** [andrewthong/covid19tracker-api#77]
I'm not sure if this is where to post this, but there's an issue with the vaccination data for Ottawa (region 3551) for today (May 28th).  It shows change_vaccinations of 17771 (which seems correct), but change_vaccinated is 485840 (I'm sure it's supposed to be in the range of 4,000). I'm sure it's a problem with the Ontario source data, but it's worth noting.

**Comment by andrewthong** [comment]
It might have been an error during initial data entry. Looks like it has already been collected.
